return {
	"sphamba/smear-cursor.nvim",
	event = "VeryLazy",
	main = "smear_cursor",
	opts = {
		smear_insert_mode = false,
		legacy_computing_symbols_support = true,
		trailing_exponent = 5,
		trailing_stiffness = 0.15,
		damping = 0.5,
		gradient_exponent = 0,
		gamma = 1,
		never_draw_over_target = true,
		hide_target_hack = true,
		-- particles_enabled = true,
		-- particle_spread = 0.4,
		-- particles_per_second = 300,
		-- particles_per_length = 50,
		-- particle_max_lifetime = 800,
		-- particle_max_initial_velocity = 20,
		-- particle_velocity_from_cursor = 0.5,
		-- particle_damping = 0.15,
		-- particle_gravity = -50,
		-- min_distance_emit_particles = 0,
	},
}
